---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: subtitler-api
    labels:
        app: subtitler-api
spec:
    replicas: 1
    selector:
        matchLabels:
            app: subtitler-api
    template:
        metadata:
            labels:
                app: subtitler-api
        spec:
            hostNetwork: true
            containers:
                - name: subtitler-api
                  image: registry.paranoids.us/subtitler-api:latest
                  ports:
                      - containerPort: 3001
                  env:
                      - name: APP_NAME
                        value: 'v1'
                      - name: HOST
                        value: '0.0.0.0'
                      - name: PORT
                        value: '3001'
            imagePullSecrets:
                - name: regcred
---
apiVersion: v1
kind: Service
metadata:
    name: subtitler-api-service
spec:
    selector:
        app: subtitler-api
    type: LoadBalancer
    externalIPs:
        - 192.168.105.108
    ports:
        - protocol: TCP
          port: 3001
          targetPort: 3001
          nodePort: 30002
